name: Release

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  bump-and-publish:
    name: Bump Version & Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # needed to push tags

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Bump patch version
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          npm version patch -m "Release v%s"

      - name: Push tag
        run: |
          git push origin HEAD --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install & Publish
        run: |
          npm ci
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 